name = "video-page"
compatibility_date = "2024-12-18"
pages_build_output_dir = "./out"

# 已移除Workers特定的配置
# main = "./workers-site/index.js"
# workers_dev = true
# [site]
# bucket = "./out"
# [build]
# command = "npm run build"
